---
name:   Geometry Lab                # The application display name
short:  Geometry                    # A shortened name for reference
appid:  edu.cornell.gdiac.code2     # Application identifier for Mac, iOS, Android
suffix: GA6C2D2B

build:  build                       # The build directory (targets are each a subdirectory)
assets: assets                      # The folder with the game assets (do not list asset)
icon:   icon.png

orientation: landscape              # The orientation for mobile devices

sources:                            # The list of the source code files
    - source/*.cpp
    - source/*.h

# This must be one of portrait, landscape, portrait-flipped, landscape-flipped,
targets:                        # The target platforms to build for
    - android                   # Android Studio
    - apple                     # XCode (note macOS and iOS use one project)
    - windows                   # Windows Sisual Studio
    - cmake                     # This supports all Desktop platform GA6C2D2B
